### ISSUE TITLE
Show file size information 

### ISSUE THREAD

**Issue by Shiba-Kar** [ronba/vscode-rive-viewer#3]
![image](https://user-images.githubusercontent.com/24454722/138544922-b1431efa-2f58-4211-9be8-addcf5c62764.png)

Show file size information

**Comment by ronba** [comment]
Thanks for the feedback! Do you mean the actual file size of the riv file?

**Comment by Shiba-Kar** [comment]
> Thanks for the feedback! Do you mean the actual file size of the riv file?

yes

**Comment by ronba** [comment]
Got it - no real plans. Currently the extension is meant to display the rive files. 
If you want to add size information to vscode the [filesize](https://marketplace.visualstudio.com/items?itemName=mkxml.vscode-filesize) extension seems like it'd be a much better fit.
